/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/brands/{brand_id}/sections/{section_id}/team-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Input */
        get: operations["get_team_input_brands__brand_id__sections__section_id__team_input_get"];
        /** Set Team Input */
        put: operations["set_team_input_brands__brand_id__sections__section_id__team_input_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_brands__brand_id__sources_get"];
        put?: never;
        /** Upload Source */
        post: operations["upload_source_brands__brand_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/research/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Research */
        post: operations["run_research_brands__brand_id__research_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/research/run-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All Research */
        post: operations["run_all_research_brands__brand_id__research_run_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Document */
        post: operations["approve_document_documents__document_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliverables/{deliverable_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deliverable */
        get: operations["get_deliverable_deliverables__deliverable_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliverables/{deliverable_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_deliverables__deliverable_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecision */
        ApprovalDecision: {
            /** Approver Id */
            approver_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note?: string | null;
        };
        /** Body_upload_source_brands__brand_id__sources_post */
        Body_upload_source_brands__brand_id__sources_post: {
            /** File */
            file: string;
            /** Source Kind */
            source_kind?: string | null;
        };
        /** Deliverable */
        Deliverable: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "insufficient_grounding";
            /** Claims */
            claims: components["schemas"]["VerifiedClaim"][];
            /** Call Site Trace */
            call_site_trace: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketResearchDocument */
        MarketResearchDocument: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "insufficient_grounding";
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["SectionResult"];
            };
            /** Call Site Trace */
            call_site_trace: {
                [key: string]: number;
            };
        };
        /** SectionResult */
        SectionResult: {
            /**
             * Section
             * @enum {string}
             */
            section: "brand_overview" | "business_goals" | "target_audience" | "customer_needs" | "market_overview" | "competitor_analysis" | "swot" | "positioning_usp" | "platform_analysis" | "trends_opportunities" | "key_takeaways";
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "insufficient_evidence" | "team_provided";
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["VerifiedClaim"][];
            /**
             * Call Site Trace
             * @default {}
             */
            call_site_trace: {
                [key: string]: number;
            };
            /** Note */
            note?: string | null;
        };
        /** SourceFile */
        SourceFile: {
            /** File Id */
            file_id: string;
            /** Brand Id */
            brand_id: string;
            /** Filename */
            filename: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "brand_material" | "analytics" | "competitor_upload";
            /**
             * Status
             * @enum {string}
             */
            status: "uploading" | "ingested" | "degraded";
            /** Degraded Reason */
            degraded_reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** TeamInputPayload */
        TeamInputPayload: {
            /** Text */
            text: string;
            /** Author */
            author?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedClaim */
        VerifiedClaim: {
            /** Claim Id */
            claim_id: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /**
             * Source Claim Ids
             * @default []
             */
            source_claim_ids: string[];
            /**
             * Block Span
             * @default [
             *       0,
             *       0
             *     ]
             */
            block_span: [
                number,
                number
            ];
            /** Verified */
            verified: boolean;
            /** Rejection Reason */
            rejection_reason?: ("missing_chunk" | "no_citation" | "missing_source_claim" | "no_source_claims") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_team_input_brands__brand_id__sections__section_id__team_input_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_team_input_brands__brand_id__sections__section_id__team_input_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamInputPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_brands__brand_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_brands__brand_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_brands__brand_id__sources_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_research_brands__brand_id__research_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_research_brands__brand_id__research_run_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_document_documents__document_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deliverable_deliverables__deliverable_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliverable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_deliverables__deliverable_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliverable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
