/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/sections/{section_id}/team-input": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team Input */
        get: operations["get_team_input_brands__brand_id__sections__section_id__team_input_get"];
        /** Set Team Input */
        put: operations["set_team_input_brands__brand_id__sections__section_id__team_input_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_brands__brand_id__sources_get"];
        put?: never;
        /** Upload Source */
        post: operations["upload_source_brands__brand_id__sources_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/research/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Research */
        post: operations["run_research_brands__brand_id__research_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/brands/{brand_id}/research/run-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run All Research */
        post: operations["run_all_research_brands__brand_id__research_run_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_documents__document_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Checkpoint */
        get: operations["get_checkpoint_documents__document_id__checkpoint_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notes */
        get: operations["list_notes_documents__document_id__notes_get"];
        put?: never;
        /** Add Note */
        post: operations["add_note_documents__document_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Document */
        post: operations["approve_document_documents__document_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/distribute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Distribute Document */
        post: operations["distribute_document_documents__document_id__distribute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Distribution */
        get: operations["get_distribution_documents__document_id__distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/documents/{document_id}/approval-gate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Approval Gate */
        get: operations["get_approval_gate_documents__document_id__approval_gate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliverables/{deliverable_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Deliverable */
        get: operations["get_deliverable_deliverables__deliverable_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deliverables/{deliverable_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve */
        post: operations["approve_deliverables__deliverable_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApprovalDecision */
        ApprovalDecision: {
            /** Approver Id */
            approver_id: string;
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "rejected";
            /** Note */
            note?: string | null;
        };
        /**
         * ApprovalGateRecord
         * @description Provenance, not the current-state field (document.status already carries
         *     that) -- the QualityCheckpoint as it stood *at decision time*, who decided,
         *     when. Dropping this at the approve boundary would be exactly the kind of
         *     confidence-loss P7 calls out.
         */
        ApprovalGateRecord: {
            /** Document Id */
            document_id: string;
            /** Approver Id */
            approver_id?: string | null;
            /** Decision */
            decision?: ("approved" | "rejected") | null;
            /** Note */
            note?: string | null;
            checkpoint: components["schemas"]["QualityCheckpoint"];
            /** Decided At */
            decided_at?: string | null;
        };
        /** Body_upload_source_brands__brand_id__sources_post */
        Body_upload_source_brands__brand_id__sources_post: {
            /** File */
            file: string;
            /** Source Kind */
            source_kind?: string | null;
        };
        /** Deliverable */
        Deliverable: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "insufficient_grounding";
            /** Claims */
            claims: components["schemas"]["VerifiedClaim"][];
            /** Call Site Trace */
            call_site_trace: {
                [key: string]: number;
            };
        };
        /** DistributionPayload */
        DistributionPayload: {
            /** Internal */
            internal: boolean;
            /** Client */
            client: boolean;
        };
        /** DistributionRecord */
        DistributionRecord: {
            /** Document Id */
            document_id: string;
            /** Internal */
            internal: boolean;
            /** Client */
            client: boolean;
            /**
             * Distributed At
             * Format: date-time
             */
            distributed_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MarketResearchDocument */
        MarketResearchDocument: {
            /** Id */
            id: string;
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "pending_approval" | "approved" | "rejected" | "insufficient_grounding";
            /** Sections */
            sections: {
                [key: string]: components["schemas"]["SectionResult"];
            };
            /** Call Site Trace */
            call_site_trace: {
                [key: string]: number;
            };
        };
        /** QualityCheckpoint */
        QualityCheckpoint: {
            /** All Sections Filled */
            all_sections_filled: boolean;
            /** Competitor Count Ok */
            competitor_count_ok: boolean;
            /** Personas Grounded */
            personas_grounded: boolean;
            /** Findings Lead To Recommendations */
            findings_lead_to_recommendations: boolean;
        };
        /** SectionResult */
        SectionResult: {
            /**
             * Section
             * @enum {string}
             */
            section: "brand_overview" | "business_goals" | "target_audience" | "customer_needs" | "market_overview" | "competitor_analysis" | "swot" | "positioning_usp" | "platform_analysis" | "trends_opportunities" | "key_takeaways";
            /** Brand Id */
            brand_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "insufficient_evidence" | "team_provided";
            /**
             * Claims
             * @default []
             */
            claims: components["schemas"]["VerifiedClaim"][];
            /**
             * Personas
             * @default []
             */
            personas: components["schemas"]["VerifiedAudiencePersona"][];
            /**
             * Call Site Trace
             * @default {}
             */
            call_site_trace: {
                [key: string]: number;
            };
            /** Note */
            note?: string | null;
        };
        /** SourceFile */
        SourceFile: {
            /** File Id */
            file_id: string;
            /** Brand Id */
            brand_id: string;
            /** Filename */
            filename: string;
            /**
             * Source Kind
             * @enum {string}
             */
            source_kind: "brand_material" | "analytics" | "competitor_upload";
            /**
             * Status
             * @enum {string}
             */
            status: "uploading" | "ingested" | "degraded";
            /** Degraded Reason */
            degraded_reason?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StrategicNote */
        StrategicNote: {
            /** Id */
            id: string;
            /** Document Id */
            document_id: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Author */
            author: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StrategicNotePayload */
        StrategicNotePayload: {
            /** Section */
            section: string;
            /** Text */
            text: string;
            /** Author */
            author: string;
        };
        /** TeamInputPayload */
        TeamInputPayload: {
            /** Text */
            text: string;
            /** Author */
            author?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerifiedAudiencePersona */
        VerifiedAudiencePersona: {
            /** Persona Id */
            persona_id: string;
            /** Section */
            section: string;
            /** Name */
            name: string;
            /**
             * Pain Points
             * @default []
             */
            pain_points: string[];
            /**
             * Interests
             * @default []
             */
            interests: string[];
            /**
             * Chunk Ids
             * @default []
             */
            chunk_ids: string[];
            /** Verified */
            verified: boolean;
            /** Rejection Reason */
            rejection_reason?: ("no_citation" | "missing_chunk" | "incomplete_persona") | null;
        };
        /** VerifiedClaim */
        VerifiedClaim: {
            /** Claim Id */
            claim_id: string;
            /** Section */
            section: string;
            /** Text */
            text: string;
            /**
             * Chunk Id
             * @default
             */
            chunk_id: string;
            /**
             * Source Claim Ids
             * @default []
             */
            source_claim_ids: string[];
            /**
             * Block Span
             * @default [
             *       0,
             *       0
             *     ]
             */
            block_span: [
                number,
                number
            ];
            /** Verified */
            verified: boolean;
            /** Rejection Reason */
            rejection_reason?: ("missing_chunk" | "no_citation" | "missing_source_claim" | "no_source_claims") | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_team_input_brands__brand_id__sections__section_id__team_input_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    } | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_team_input_brands__brand_id__sections__section_id__team_input_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
                section_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamInputPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_brands__brand_id__sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFile"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_source_brands__brand_id__sources_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_brands__brand_id__sources_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_research_brands__brand_id__research_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_all_research_brands__brand_id__research_run_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                brand_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_checkpoint_documents__document_id__checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QualityCheckpoint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notes_documents__document_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategicNote"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_documents__document_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategicNotePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategicNote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_document_documents__document_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketResearchDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    distribute_document_documents__document_id__distribute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DistributionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_distribution_documents__document_id__distribution_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DistributionRecord"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_approval_gate_documents__document_id__approval_gate_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalGateRecord"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deliverable_deliverables__deliverable_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliverable_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_deliverables__deliverable_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deliverable_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalDecision"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deliverable"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
